export enum AuctionLotStatus {
  NOT_BID = 'NOT_BID',
  BID_SUBMITTED = 'BID_SUBMITTED',
  WON = 'WON',
  LOST = 'LOST',
  PARTIALLY_PICKED = 'PARTIALLY_PICKED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
