export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',

  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',

  CREATE_ADMIN = 'CREATE_ADMIN',
  CREATE_STAFF = 'CREATE_STAFF',

  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  CREATE_INVOICE = 'CREATE_INVOICE',
  UPDATE_INVOICE = 'UPDATE_INVOICE',
  DELETE_INVOICE = 'DELETE_INVOICE',
  CREATE_VECHILE_INVOICE = 'CREATE_VECHILE_INVOICE',
  UPDATE_VECHILE_INVOICE = 'UPDATE_VECHILE_INVOICE',
  DELETE_VECHILE_INVOICE = 'DELETE_VECHILE_INVOICE',

  REFRESH_TOKEN = 'REFRESH_TOKEN',
  RESET_PASSWORD = 'RESET_PASSWORD',

  API_CALL = 'API_CALL',
}
