export enum LotLifecycleEventType {
  OUTCOME_CHANGED = 'OUTCOME_CHANGED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  ACCEPTANCE_LETTER_UPDATED = 'ACCEPTANCE_LETTER_UPDATED',
  DELIVERY_UPDATED = 'DELIVERY_UPDATED',
  GATE_PASS_UPLOADED = 'GATE_PASS_UPLOADED',
  RCM_UPDATED = 'RCM_UPDATED',
}
