export enum YardVehicleStatus {
  AWAITING_ARRIVAL = 'AWAITING_ARRIVAL',
  GATE_IN = 'GATE_IN',
  PARKED = 'PARKED',
  DISMANTLING_IN_PROGRESS = 'DISMANTLING_IN_PROGRESS',
  DISMANTLED = 'DISMANTLED',
  EXITED = 'EXITED',
}
